#!/usr/bin/env bash

#Cloning | Updating dotfiles repo locally
if [ -d "$HOME/dotfiles" ]; then
  (cd $HOME/dotfiles ; git reset --hard && git clean -f -d && git pull origin bspwm)
else
  (cd $HOME ; git clone https://github.com/xd003/dotfiles)
fi

# Deleting already existing configs to avoid conflicts
(cd $HOME/dotfiles/.config ; find . -maxdepth 1 -mindepth 1 -type d -exec rm -rf $HOME/.config/{} \;)

#Cleaning Home Directory
(cd $HOME ; rm -rf .p10k.zsh .zshrc zshrc-personal history .zcompdump .lesshst .lyxauth .bashrc .bash_profile .bash_history .bash_logout .profile .zprofile Scripts
(cd $HOME/dotfiles/.bin ; find . -maxdepth 1 -mindepth 1 -exec rm -rf $HOME/.bin/{} \;)

#Cleaning scripts & other misc stuffs
(cd $HOME/dotfiles/.local/bin ; find . -maxdepth 1 -mindepth 1 -exec rm -rf $HOME/.local/bin/{} \;)
(cd $HOME/dotfiles/.local/share/fonts ; find . -maxdepth 1 -mindepth 1 -exec rm -rf $HOME/local/share/fonts/{} \;)

#Creating Symlinks
mkdir -p $HOME/.config && ln -sf $HOME/dotfiles/.config/* $HOME/.config/
mkdir -p $HOME/.bin && ln -sf $HOME/dotfiles/.bin/* $HOME/.bin/
mkdir -p $HOME/.local/bin && ln -sf $HOME/dotfiles/.local/bin/* $HOME/.local/bin/
mkdir -p $HOME/Scripts && ln -sf $HOME/dotfiles/Scripts/* $HOME/Scripts/
find $HOME/dotfiles -maxdepth 1 -mindepth 1 -type f -exec ln -sf {} $HOME/ \;

#Giving necessary permission to executables
sudo chmod u+x $HOME/.bin/* $HOME/.local/bin/* $HOME/Scripts/*
find $HOME/dotfiles/.config -type f -name "*rc" -exec sudo chmod u+x {} \;

echo && echo "Dotfiles successfully restored"
