#!/usr/bin/env bash

#Cloning | Updating dotfiles repo locally
if [ -d "$HOME/dotfiles" ]; then
  (cd $HOME/dotfiles ; git add -A && git commit -m "local updates" && git push origin bspwm && git pull origin bspwm)
else
  git clone https://github.com/xd003/dotfiles
fi

# Deleting already existing configs to avoid conflicts
(cd $HOME/dotfiles/config ; find . -exec rm -rf $HOME/.config/{} \;)

#Cleaning Home
rm -rf $HOME/.zshrc 
$HOME/history 
$HOME/.p10k.zsh 
$HOME/.profile 
$HOME/.bashrc 
$HOME/.bash_profile
$HOME/Scripts
$HOME/.bin




#Cleaning scripts & other misc stuffs
(cd $HOME/dotfiles/.local/bin ; find . -exec rm -rf $HOME/.config/.local/bin/{} \;)
(cd $HOME/dotfiles/.local/share/fonts ; find . -exec rm -rf $HOME/local/share/fonts/{} \;)
