#!/usr/bin/env bash

# Deleting already existing configs to avoid conflicts
rm -rf $HOME/.config/Kvantum
rm -rf $HOME/.config/alacritty
rm -rf $HOME/.config/bspwm
rm -rf $HOME/.config/dunst
rm -rf $HOME/.config/jgmenu
rm -rf $HOME/.config/mpv
rm -rf $HOME/.config/neofetch
rm -rf $HOME/.config/neovim
rm -rf $HOME/.config/networkmanager-dmenu
rm -rf $HOME/.config/pipewire
rm -rf $HOME/.config/ranger
rm -rf $HOME/.config/rofi
rm -rf $HOME/.config/sxkhd
rm -rf $HOME/.config/touchegg
rm -rf $HOME/.config/zathura
rm -rf $HOME/.config/zsh

#Cleaning Home
rm -rf $HOME/.zshrc 
$HOME/history 
$HOME/.p10k.zsh 
$HOME/.profile 
$HOME/.bashrc 
$HOME/.bash_profile
$HOME/Scripts
$HOME/.bin

#Cloning | Updating dotfiles repo locally


#Cleaning scripts & other misc stuffs
cd $HOME/dotfiles/.local/bin ; find . -exec rm -rf $HOME/.config/.local/bin/{} \;
cd $HOME/dotfiles/.local/share/fonts ; find . -exec rm -rf $HOME/local/share/fonts/{} \;
