#!/usr/bin/env bash

pid=$HOME/Videos/screenrecord.pid

# Add check for existence of mypidfile 
if [ -f $pid ]; then
    pkill -9 -f $HOME/.bin/screenrecord
    dunstify "Screen Recording has been stopped"
    exit
fi

# Create a file with current PID to indicate that process is running.
echo $$ > "$pid"

dunstify "Screen Recording has been started"
RES=$(xrandr -q | sed '3q;d' | perl -pe 's|^\s{3}(\w+)\s+(\d+).*|$1|g')
RATE=$(xrandr -q | sed '3q;d' | perl -pe 's|^\s{3}(\w+)\s+(\d+).*|$2|g')

ffmpeg -f x11grab \
-framerate $RATE \
-video_size $RES \
-i $DISPLAY \
-preset ultrafast \
-vaapi_device /dev/dri/renderD128 \
-c:v h264_vaapi \
-vf 'hwupload,scale_vaapi=format=nv12' \
$HOME/Videos/"$(date +%Y%m%d_%H%M%S)".mp4

rm -rf $pid
