#!/usr/bin/env bash

# Check if script is already running
check="$(pgrep -fl ffmpeg)"
if [ -n "$check" ]; then
    dunstify "Screen Recording has been stopped"
    killall --user $USER  --ignore-case  --signal INT ffmpeg
else
  dunstify "Screen Recording has been started"
  RES=$(xrandr -q | sed '3q;d' | perl -pe 's|^\s{3}(\w+)\s+(\d+).*|$1|g')
  RATE=$(xrandr -q | sed '3q;d' | perl -pe 's|^\s{3}(\w+)\s+(\d+).*|$2|g')

  ffmpeg -f x11grab \
  -framerate $RATE \
  -video_size $RES \
  -i $DISPLAY \
  -preset ultrafast \
  -vaapi_device /dev/dri/renderD128 \
  -c:v h264_vaapi \
  -vf 'hwupload,scale_vaapi=format=nv12' \
  $HOME/Videos/"$(date +%d%_m%_%H:%M)".mp4
fi
