#!/bin/bash

#     __
#    / /_  _________ _      ______ ___
#   / __ \/ ___/ __ \ | /| / / __ `__ \
#  / /_/ (__  ) /_/ / |/ |/ / / / / / /
# /_.___/____/ .___/|__/|__/_/ /_/ /_/
#           /_/
#

# Restore wallpaper
nitrogen --restore &

# Launch polybar
bash "$HOME/.config/bspwm/polybar/launch.sh" &

# Fix the pointer for BSPWM
xsetroot -cursor_name left_ptr &

# Set bspc configurations
bspc config border_width 2
bspc config window_gap 0
bspc config split_ratio 0.50

# Colors
bspc config focused_border_color "#7bc5e4"
bspc config normal_border_color "#32344a"
bspc config active_border_color "#444b6a"

bspc config borderless_monocle true
bspc config gapless_monocle true
# bspc config paddingless_monocle true
bspc config single_monocle false
bspc config focus_follows_pointer true

# MOD key control
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_corner

# Autostart apps
eval "$HOME/.config/bspwm/autostart.sh" &

# Set App rules
# Force floating mode
declare -a floats=()
for i in "${floats[@]}"; do
	bspc rule -a "$i" manage=on state=floating follow=on focus=on center=true
done

# Force tile windows
declare -a tiled=()
for i in "${tiled[@]}"; do
	bspc rule -a "$i" manage=on state=tiled
done

# Force full screen windows
declare -a fullscreen=(Zathura mpv)
for i in "${fullscreen[@]}"; do
	bspc rule -a "$i" manage=on state=fullscreen
done

# Kill if already running & Enable Super Keys For Menu
killall -9 ksuperkey
ksuperkey -e 'Super_L=Alt_L|F1' &
ksuperkey -e 'Super_R=Alt_L|F1' &

# Polkit agent
if [[ ! $(pidof xfce-polkit) ]]; then
	/usr/lib/xfce-polkit/xfce-polkit &
fi

# Delete existing hooks and restart them
pkill -9 -f /home/xd003/.config/bspwm/scripts/switch_emptyws.sh
eval /home/xd003/.config/bspwm/scripts/switch_emptyws.sh &

#External Workspace rule
bspc config external_rules_command $HOME/.config/bspwm/scripts/workspace_rules.sh
